title: Matthew Durbin
description: PhD Candidate of Nuclear Engineeering
show_downloads: true
google_analytics:
theme: jekyll-theme-slate

Navigation:
- text: About Me
  url: /
  
- text: Research
  url: /research
  
- text: CV
  url: /CV
 
-text: Projects
 url: /projects
