title: Matthew Durbin
description: PhD Candidate of Nuclear Engineering
show_downloads: true
google_analytics:
theme: jekyll-theme-slate

Navigation:
- text: About Me
  url: /
  
- text: Research
  url: /research
  
- text: CV
  url: /CV
 
- text: Projects
  url: /projects
  
- text: Involvement
  url: /involvement

- text: datenight
  url: /datenight
